---
compilation:
  cloud_properties:
    availability_zone: us-east-1a
    instance_type: c3.large
  network: nats1
  reuse_compilation_vms: true
  workers: 6
director_uuid: 485f5259-a5a9-4ac6-a9d7-7a54a00c2ace 
jobs:
- instances: 1
  name: nats_z1
  networks:
  - name: nats1
    static_ips:
    - 10.10.19.101
  properties:
    networks:
      apps: nats1
  resource_pool: gnatsd_z1
  templates:
  - name: varz_gnats_datadog
    release: nats-stress
  - name: nats
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 0
  name: nats_z2
  networks:
  - name: nats2
    static_ips:
  properties:
    networks:
      apps: nats2
  resource_pool: gnatsd_z2
  templates:
  - name: varz_gnats_datadog
    release: nats-stress
  - name: nats
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: ???
  name: ruby_client_z1
  networks:
  - name: nats1
    static_ips:
    - 10.10.19.102
    - 10.10.19.103
    # - 10.10.19.104
    # - 10.10.19.105
    # - 10.10.19.114
    # - 10.10.19.115
    # - 10.10.19.116
    # - 10.10.19.106
    # - 10.10.19.107
    # - 10.10.19.108
    # - 10.10.19.109
    # - 10.10.19.117
    # - 10.10.19.110
    # - 10.10.19.111
    # - 10.10.19.112
    # - 10.10.19.113
    # - 10.10.19.120
    # - 10.10.19.122
  properties:
    nats:
      machines:
      - 10.10.19.101
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: ruby_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: ???
  name: ruby_client_z2
  networks:
  - name: nats2
    static_ips:
    - 10.10.81.152
    - 10.10.81.153
    # - 10.10.81.154
    # - 10.10.81.155
    # - 10.10.81.164
    # - 10.10.81.165
    # - 10.10.81.166
    # - 10.10.81.156
    # - 10.10.81.157
    # - 10.10.81.158
    # - 10.10.81.159
    # - 10.10.81.167
    # - 10.10.81.160
    # - 10.10.81.161
    # - 10.10.81.162
    # - 10.10.81.163
    # - 10.10.81.170
    # - 10.10.81.171    
  properties:
    nats:
      machines:
      - 10.10.19.101
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: ruby_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 0
  name: yagnats_og_client_z1
  networks:
  - name: nats1
    static_ips: []
  properties:
    nats:
      machines:
      - 10.10.19.101
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: yagnats_og_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 0
  name: yagnats_og_client_z2
  networks:
  - name: nats2
    static_ips: []
  properties:
    nats:
      machines:
      - 10.10.19.101
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: yagnats_og_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 0
  name: yagnats_apcera_client_z1
  networks:
  - name: nats1
    static_ips:
  properties:
    nats:
      machines:
      - 10.10.19.101
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: yagnats_apcera_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 0
  name: yagnats_apcera_client_z2
  networks:
  - name: nats2
    static_ips:
  properties:
    nats:
      machines:
      - 10.10.19.101
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: yagnats_apcera_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
name: nats-stress
networks:
- name: cf1
  subnets:
  - cloud_properties:
      security_groups:
      - cf
      subnet: subnet-56bfab22
    dns:
    - 10.10.0.2
    gateway: 10.10.16.1
    name: default_unused
    range: 10.10.16.0/20
    reserved:
    - 10.10.16.2 - 10.10.16.9
    - 10.10.18.0 - 10.10.18.255
    static:
    - 10.10.16.10 - 10.10.16.255
  type: manual
- name: cf2
  subnets:
  - cloud_properties:
      security_groups:
      - cf
      subnet: subnet-4aacfd62
    dns:
    - 10.10.0.2
    gateway: 10.10.80.1
    name: default_unused
    range: 10.10.80.0/20
    reserved:
    - 10.10.80.2 - 10.10.80.9
    - 10.10.81.0 - 10.10.80.10
    static:
    - 10.10.80.10 - 10.10.80.254
  type: manual
- name: nats1
  subnets:
  - cloud_properties:
      security_groups:
      - open
      subnet: subnet-56bfab22
    dns:
    - 10.10.0.2
    gateway: 10.10.16.1
    name: default_unused
    range: 10.10.16.0/20
    reserved:
    - 10.10.16.2 - 10.10.16.255
    - 10.10.17.0 - 10.10.17.255
    - 10.10.18.0 - 10.10.18.255
    static:
    - 10.10.19.100 - 10.10.19.255
  type: manual
- name: nats2
  subnets:
  - cloud_properties:
      security_groups:
      - open
      subnet: subnet-4aacfd62
    dns:
    - 10.10.0.2
    gateway: 10.10.80.1
    name: default_unused
    range: 10.10.80.0/20
    reserved:
    - 10.10.80.2 - 10.10.80.255
    - 10.10.81.0 - 10.10.80.10
    static:
    - 10.10.81.150 - 10.10.81.255
  type: manual
properties:
  datadog_api_key: 222f75804fa0833a975ef87e5d75a8b8 
  nats:
    address: 10.10.19.101
    debug: false
    machines:
    - 10.10.19.101
    monitor_port: 5001
    password: c1oudc0wc1oudc0w
    port: 4222
    prof_port: 0
    trace: false
    user: nats
    z1_machines:
    - 10.10.19.101
    z2_machines:
    - 10.10.19.101
  payload_size_in_bytes: 300
  population: 36
  publish_interval_in_seconds: 0.05
releases:
- name: nats-stress
  version: latest
resource_pools:
- cloud_properties:
    availability_zone: us-east-1a
    instance_type: m3.medium
  name: medium_z1
  network: nats1
  size: 18
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: 2710
- cloud_properties:
    availability_zone: us-east-1d
    instance_type: m3.medium
  name: medium_z2
  network: nats2
  size: 18
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: 2710
- cloud_properties:
    availability_zone: us-east-1a
    instance_type: m3.medium
  name: gnatsd_z1
  network: nats1
  size: 1
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: 2710
- cloud_properties:
    availability_zone: us-east-1d
    instance_type: m3.medium
  name: gnatsd_z2
  network: nats2
  size: 1
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: 2710
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 10
  serial: true
  update_watch_time: 1000-180001
