compilation:
  cloud_properties:
    availability_zone: us-east-1d
    instance_type: c3.large
  network: nats1
  reuse_compilation_vms: true
  workers: 6
director_uuid: c3e3311f-08c9-4809-8083-4aa184fd24da
jobs:
- instances: 1
  name: nats_z1
  networks:
  - name: nats1
    static_ips:
    - 10.10.211.13
  properties:
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: nats
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: nats_z2
  networks:
  - name: nats2
    static_ips:
    - 10.10.212.13
  properties:
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: nats
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 12
  name: ruby_client_z1
  networks:
  - name: nats1
    static_ips:
    - 10.10.211.14
    - 10.10.211.15
    - 10.10.211.16
    - 10.10.211.17
    - 10.10.211.26
    - 10.10.211.27
    - 10.10.211.28
    - 10.10.211.18
    - 10.10.211.19
    - 10.10.211.20
    - 10.10.211.21
    - 10.10.211.29
  properties:
    nats:
      machines:
      - 10.10.211.13
      - 10.10.212.13
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: ruby_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 12
  name: ruby_client_z2
  networks:
  - name: nats2
    static_ips:
    - 10.10.212.14
    - 10.10.212.15
    - 10.10.212.16
    - 10.10.212.17
    - 10.10.212.26
    - 10.10.212.27
    - 10.10.212.28
    - 10.10.212.18
    - 10.10.212.19
    - 10.10.212.20
    - 10.10.212.21
    - 10.10.212.29
  properties:
    nats:
      machines:
      - 10.10.212.13
      - 10.10.211.13
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: ruby_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 0
  name: yagnats_og_client_z1
  networks:
  - name: nats1
    static_ips: []
  properties:
    nats:
      machines:
      - 10.10.211.13
      - 10.10.212.13
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: yagnats_og_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 0
  name: yagnats_og_client_z2
  networks:
  - name: nats2
    static_ips: []
  properties:
    nats:
      machines:
      - 10.10.212.13
      - 10.10.211.13
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: yagnats_og_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 6
  name: yagnats_apcera_client_z1
  networks:
  - name: nats1
    static_ips:
    - 10.10.211.22
    - 10.10.211.23
    - 10.10.211.24
    - 10.10.211.25
    - 10.10.211.32
    - 10.10.211.33
  properties:
    nats:
      machines:
      - 10.10.211.13
      - 10.10.212.13
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: yagnats_apcera_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 6
  name: yagnats_apcera_client_z2
  networks:
  - name: nats2
    static_ips:
    - 10.10.212.22
    - 10.10.212.23
    - 10.10.212.24
    - 10.10.212.25
    - 10.10.212.32
    - 10.10.212.33
  properties:
    nats:
      machines:
      - 10.10.212.13
      - 10.10.211.13
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: yagnats_apcera_client
    release: nats-stress
  - name: metrics
    release: nats-stress
  - name: panel
    release: nats-stress
meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
name: nats-stress
networks:
- name: nats1
  subnets:
  - cloud_properties:
      security_groups:
      - cf
      subnet: subnet-889b29d1
    dns:
    - 10.10.0.2
    gateway: 10.10.211.1
    name: nats_stress1
    range: 10.10.211.0/24
    reserved: null
    static:
    - 10.10.211.12 - 10.10.211.134
  type: manual
- name: nats2
  subnets:
  - cloud_properties:
      security_groups:
      - cf
      subnet: subnet-931280e4
    dns:
    - 10.10.0.2
    gateway: 10.10.212.1
    name: nats_stress2
    range: 10.10.212.0/24
    reserved: null
    static:
    - 10.10.212.12 - 10.10.212.134
  type: manual
properties:
  datadog_api_key: 222f75804fa0833a975ef87e5d75a8b8
  nats:
    address: 10.10.211.13
    debug: false
    machines:
    - 10.10.211.13
    - 10.10.212.13
    monitor_port: 0
    password: nats
    port: 4222
    prof_port: 0
    trace: false
    user: nats
    z1_machines:
    - 10.10.211.13
    - 10.10.212.13
    z2_machines:
    - 10.10.212.13
    - 10.10.211.13
  payload_size_in_bytes: 300
  population: 12
  publish_interval_in_seconds: 0.05
releases:
- name: nats-stress
  version: latest
resource_pools:
- cloud_properties:
    availability_zone: us-east-1d
    instance_type: m3.medium
  name: medium_z1
  network: nats1
  size: 19
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    availability_zone: us-east-1c
    instance_type: m3.medium
  name: medium_z2
  network: nats2
  size: 19
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 8
  serial: true
  update_watch_time: 1000-180000

