compilation:
  cloud_properties:
    name: random
  network: nats1
  reuse_compilation_vms: true
  workers: 6
director_uuid: c3e3311f-08c9-4809-8083-4aa184fd24da
jobs:
- instances: 1
  name: nats_z1
  networks:
  - name: nats1
    static_ips:
    - 10.244.5.6
  properties:
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: nats
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: nats_z2
  networks:
  - name: nats2
    static_ips:
    - 10.244.6.6
  properties:
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: nats
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: ruby_client_z1
  networks:
  - name: nats1
    static_ips:
    - 10.244.5.10
  properties:
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: ruby_client
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: ruby_client_z2
  networks:
  - name: nats2
    static_ips:
    - 10.244.6.10
  properties:
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: ruby_client
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: yagnats_og_client_z1
  networks:
  - name: nats1
    static_ips:
    - 10.244.5.14
  properties:
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: yagnats_og_client
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: yagnats_og_client_z2
  networks:
  - name: nats2
    static_ips:
    - 10.244.6.14
  properties:
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: yagnats_og_client
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: yagnats_apcera_client_z1
  networks:
  - name: nats1
    static_ips:
    - 10.244.5.18
  properties:
    networks:
      apps: nats1
  resource_pool: medium_z1
  templates:
  - name: yagnats_apcera_client
    release: nats-stress
  - name: panel
    release: nats-stress
- instances: 1
  name: yagnats_apcera_client_z2
  networks:
  - name: nats2
    static_ips:
    - 10.244.6.18
  properties:
    networks:
      apps: nats2
  resource_pool: medium_z2
  templates:
  - name: yagnats_apcera_client
    release: nats-stress
  - name: panel
    release: nats-stress
meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
name: nats-stress-warden
networks:
- name: nats1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.5.0/30
    reserved:
    - 10.244.5.1
    static:
    - 10.244.5.2
  - cloud_properties:
      name: random
    range: 10.244.5.4/30
    reserved:
    - 10.244.5.5
    static:
    - 10.244.5.6
  - cloud_properties:
      name: random
    range: 10.244.5.8/30
    reserved:
    - 10.244.5.9
    static:
    - 10.244.5.10
  - cloud_properties:
      name: random
    range: 10.244.5.12/30
    reserved:
    - 10.244.5.13
    static:
    - 10.244.5.14
  - cloud_properties:
      name: random
    range: 10.244.5.16/30
    reserved:
    - 10.244.5.17
    static:
    - 10.244.5.18
  - cloud_properties:
      name: random
    range: 10.244.5.20/30
    reserved:
    - 10.244.5.21
    static:
    - 10.244.5.22
  - cloud_properties:
      name: random
    range: 10.244.5.24/30
    reserved:
    - 10.244.5.25
    static:
    - 10.244.5.26
  - cloud_properties:
      name: random
    range: 10.244.5.28/30
    reserved:
    - 10.244.5.29
    static:
    - 10.244.5.30
  - cloud_properties:
      name: random
    range: 10.244.5.32/30
    reserved:
    - 10.244.5.33
    static:
    - 10.244.5.34
  - cloud_properties:
      name: random
    range: 10.244.5.36/30
    reserved:
    - 10.244.5.37
    static:
    - 10.244.5.38
  - cloud_properties:
      name: random
    range: 10.244.5.40/30
    reserved:
    - 10.244.5.41
    static:
    - 10.244.5.42
  - cloud_properties:
      name: random
    range: 10.244.5.44/30
    reserved:
    - 10.244.5.45
    static:
    - 10.244.5.46
  - cloud_properties:
      name: random
    range: 10.244.5.48/30
    reserved:
    - 10.244.5.49
    static:
    - 10.244.5.50
  - cloud_properties:
      name: random
    range: 10.244.5.52/30
    reserved:
    - 10.244.5.53
    static:
    - 10.244.5.54
  - cloud_properties:
      name: random
    range: 10.244.5.56/30
    reserved:
    - 10.244.5.57
    static:
    - 10.244.5.58
  - cloud_properties:
      name: random
    range: 10.244.5.60/30
    reserved:
    - 10.244.5.61
    static:
    - 10.244.5.62
  - cloud_properties:
      name: random
    range: 10.244.5.64/30
    reserved:
    - 10.244.5.65
    static:
    - 10.244.5.66
  - cloud_properties:
      name: random
    range: 10.244.5.68/30
    reserved:
    - 10.244.5.69
    static:
    - 10.244.5.70
  - cloud_properties:
      name: random
    range: 10.244.5.72/30
    reserved:
    - 10.244.5.73
    static:
    - 10.244.5.74
  - cloud_properties:
      name: random
    range: 10.244.5.76/30
    reserved:
    - 10.244.5.77
    static:
    - 10.244.5.78
  - cloud_properties:
      name: random
    range: 10.244.5.80/30
    reserved:
    - 10.244.5.81
    static:
    - 10.244.5.82
  - cloud_properties:
      name: random
    range: 10.244.5.84/30
    reserved:
    - 10.244.5.85
    static:
    - 10.244.5.86
  - cloud_properties:
      name: random
    range: 10.244.5.88/30
    reserved:
    - 10.244.5.89
    static:
    - 10.244.5.90
  - cloud_properties:
      name: random
    range: 10.244.5.92/30
    reserved:
    - 10.244.5.93
    static:
    - 10.244.5.94
  - cloud_properties:
      name: random
    range: 10.244.5.96/30
    reserved:
    - 10.244.5.97
    static:
    - 10.244.5.98
  - cloud_properties:
      name: random
    range: 10.244.5.100/30
    reserved:
    - 10.244.5.101
    static:
    - 10.244.5.102
  - cloud_properties:
      name: random
    range: 10.244.5.104/30
    reserved:
    - 10.244.5.105
    static:
    - 10.244.5.106
  - cloud_properties:
      name: random
    range: 10.244.5.108/30
    reserved:
    - 10.244.5.109
    static:
    - 10.244.5.110
  - cloud_properties:
      name: random
    range: 10.244.5.112/30
    reserved:
    - 10.244.5.113
    static:
    - 10.244.5.114
  - cloud_properties:
      name: random
    range: 10.244.5.116/30
    reserved:
    - 10.244.5.117
    static:
    - 10.244.5.118
  - cloud_properties:
      name: random
    range: 10.244.5.120/30
    reserved:
    - 10.244.5.121
    static:
    - 10.244.5.122
  - cloud_properties:
      name: random
    range: 10.244.5.124/30
    reserved:
    - 10.244.5.125
    static:
    - 10.244.5.126
  - cloud_properties:
      name: random
    range: 10.244.5.128/30
    reserved:
    - 10.244.5.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.132/30
    reserved:
    - 10.244.5.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.136/30
    reserved:
    - 10.244.5.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.140/30
    reserved:
    - 10.244.5.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.144/30
    reserved:
    - 10.244.5.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.148/30
    reserved:
    - 10.244.5.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.152/30
    reserved:
    - 10.244.5.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.156/30
    reserved:
    - 10.244.5.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.160/30
    reserved:
    - 10.244.5.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.164/30
    reserved:
    - 10.244.5.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.168/30
    reserved:
    - 10.244.5.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.172/30
    reserved:
    - 10.244.5.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.176/30
    reserved:
    - 10.244.5.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.180/30
    reserved:
    - 10.244.5.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.184/30
    reserved:
    - 10.244.5.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.188/30
    reserved:
    - 10.244.5.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.192/30
    reserved:
    - 10.244.5.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.196/30
    reserved:
    - 10.244.5.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.200/30
    reserved:
    - 10.244.5.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.204/30
    reserved:
    - 10.244.5.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.208/30
    reserved:
    - 10.244.5.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.212/30
    reserved:
    - 10.244.5.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.216/30
    reserved:
    - 10.244.5.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.220/30
    reserved:
    - 10.244.5.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.224/30
    reserved:
    - 10.244.5.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.228/30
    reserved:
    - 10.244.5.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.232/30
    reserved:
    - 10.244.5.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.236/30
    reserved:
    - 10.244.5.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.240/30
    reserved:
    - 10.244.5.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.244/30
    reserved:
    - 10.244.5.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.248/30
    reserved:
    - 10.244.5.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.5.252/30
    reserved:
    - 10.244.5.253
    static: []
- name: nats2
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.6.0/30
    reserved:
    - 10.244.6.1
    static:
    - 10.244.6.2
  - cloud_properties:
      name: random
    range: 10.244.6.4/30
    reserved:
    - 10.244.6.5
    static:
    - 10.244.6.6
  - cloud_properties:
      name: random
    range: 10.244.6.8/30
    reserved:
    - 10.244.6.9
    static:
    - 10.244.6.10
  - cloud_properties:
      name: random
    range: 10.244.6.12/30
    reserved:
    - 10.244.6.13
    static:
    - 10.244.6.14
  - cloud_properties:
      name: random
    range: 10.244.6.16/30
    reserved:
    - 10.244.6.17
    static:
    - 10.244.6.18
  - cloud_properties:
      name: random
    range: 10.244.6.20/30
    reserved:
    - 10.244.6.21
    static:
    - 10.244.6.22
  - cloud_properties:
      name: random
    range: 10.244.6.24/30
    reserved:
    - 10.244.6.25
    static:
    - 10.244.6.26
  - cloud_properties:
      name: random
    range: 10.244.6.28/30
    reserved:
    - 10.244.6.29
    static:
    - 10.244.6.30
  - cloud_properties:
      name: random
    range: 10.244.6.32/30
    reserved:
    - 10.244.6.33
    static:
    - 10.244.6.34
  - cloud_properties:
      name: random
    range: 10.244.6.36/30
    reserved:
    - 10.244.6.37
    static:
    - 10.244.6.38
  - cloud_properties:
      name: random
    range: 10.244.6.40/30
    reserved:
    - 10.244.6.41
    static:
    - 10.244.6.42
  - cloud_properties:
      name: random
    range: 10.244.6.44/30
    reserved:
    - 10.244.6.45
    static:
    - 10.244.6.46
  - cloud_properties:
      name: random
    range: 10.244.6.48/30
    reserved:
    - 10.244.6.49
    static:
    - 10.244.6.50
  - cloud_properties:
      name: random
    range: 10.244.6.52/30
    reserved:
    - 10.244.6.53
    static:
    - 10.244.6.54
  - cloud_properties:
      name: random
    range: 10.244.6.56/30
    reserved:
    - 10.244.6.57
    static:
    - 10.244.6.58
  - cloud_properties:
      name: random
    range: 10.244.6.60/30
    reserved:
    - 10.244.6.61
    static:
    - 10.244.6.62
  - cloud_properties:
      name: random
    range: 10.244.6.64/30
    reserved:
    - 10.244.6.65
    static:
    - 10.244.6.66
  - cloud_properties:
      name: random
    range: 10.244.6.68/30
    reserved:
    - 10.244.6.69
    static:
    - 10.244.6.70
  - cloud_properties:
      name: random
    range: 10.244.6.72/30
    reserved:
    - 10.244.6.73
    static:
    - 10.244.6.74
  - cloud_properties:
      name: random
    range: 10.244.6.76/30
    reserved:
    - 10.244.6.77
    static:
    - 10.244.6.78
  - cloud_properties:
      name: random
    range: 10.244.6.80/30
    reserved:
    - 10.244.6.81
    static:
    - 10.244.6.82
  - cloud_properties:
      name: random
    range: 10.244.6.84/30
    reserved:
    - 10.244.6.85
    static:
    - 10.244.6.86
  - cloud_properties:
      name: random
    range: 10.244.6.88/30
    reserved:
    - 10.244.6.89
    static:
    - 10.244.6.90
  - cloud_properties:
      name: random
    range: 10.244.6.92/30
    reserved:
    - 10.244.6.93
    static:
    - 10.244.6.94
  - cloud_properties:
      name: random
    range: 10.244.6.96/30
    reserved:
    - 10.244.6.97
    static:
    - 10.244.6.98
  - cloud_properties:
      name: random
    range: 10.244.6.100/30
    reserved:
    - 10.244.6.101
    static:
    - 10.244.6.102
  - cloud_properties:
      name: random
    range: 10.244.6.104/30
    reserved:
    - 10.244.6.105
    static:
    - 10.244.6.106
  - cloud_properties:
      name: random
    range: 10.244.6.108/30
    reserved:
    - 10.244.6.109
    static:
    - 10.244.6.110
  - cloud_properties:
      name: random
    range: 10.244.6.112/30
    reserved:
    - 10.244.6.113
    static:
    - 10.244.6.114
  - cloud_properties:
      name: random
    range: 10.244.6.116/30
    reserved:
    - 10.244.6.117
    static:
    - 10.244.6.118
  - cloud_properties:
      name: random
    range: 10.244.6.120/30
    reserved:
    - 10.244.6.121
    static:
    - 10.244.6.122
  - cloud_properties:
      name: random
    range: 10.244.6.124/30
    reserved:
    - 10.244.6.125
    static:
    - 10.244.6.126
  - cloud_properties:
      name: random
    range: 10.244.6.128/30
    reserved:
    - 10.244.6.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.132/30
    reserved:
    - 10.244.6.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.136/30
    reserved:
    - 10.244.6.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.140/30
    reserved:
    - 10.244.6.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.144/30
    reserved:
    - 10.244.6.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.148/30
    reserved:
    - 10.244.6.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.152/30
    reserved:
    - 10.244.6.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.156/30
    reserved:
    - 10.244.6.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.160/30
    reserved:
    - 10.244.6.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.164/30
    reserved:
    - 10.244.6.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.168/30
    reserved:
    - 10.244.6.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.172/30
    reserved:
    - 10.244.6.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.176/30
    reserved:
    - 10.244.6.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.180/30
    reserved:
    - 10.244.6.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.184/30
    reserved:
    - 10.244.6.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.188/30
    reserved:
    - 10.244.6.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.192/30
    reserved:
    - 10.244.6.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.196/30
    reserved:
    - 10.244.6.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.200/30
    reserved:
    - 10.244.6.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.204/30
    reserved:
    - 10.244.6.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.208/30
    reserved:
    - 10.244.6.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.212/30
    reserved:
    - 10.244.6.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.216/30
    reserved:
    - 10.244.6.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.220/30
    reserved:
    - 10.244.6.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.224/30
    reserved:
    - 10.244.6.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.228/30
    reserved:
    - 10.244.6.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.232/30
    reserved:
    - 10.244.6.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.236/30
    reserved:
    - 10.244.6.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.240/30
    reserved:
    - 10.244.6.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.244/30
    reserved:
    - 10.244.6.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.248/30
    reserved:
    - 10.244.6.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.252/30
    reserved:
    - 10.244.6.253
    static: []
properties:
  nats:
    address: 10.244.5.6
    debug: false
    machines:
    - 10.244.5.6
    - 10.244.6.6
    monitor_port: 0
    password: nats
    port: 4222
    prof_port: 0
    trace: false
    user: nats
releases:
- name: nats-stress
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: medium_z1
  network: nats1
  size: 4
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    name: random
  name: medium_z2
  network: nats2
  size: 4
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: true
  update_watch_time: 1000-180000

