meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 8
  canary_watch_time: 1000-180000
  update_watch_time: 1000-180000
  serial: true

properties:
  nats:
    user: nats
    password: nats
    address: (( jobs.nats_z1.networks.nats1.static_ips.[0] ))

jobs:
  # specify nats static IP
  - name: nats_z1
    instances: 1
    networks:
      - name: nats1
        static_ips: (( static_ips(1) ))

  - name: nats_z2
    instances: 1
    networks:
      - name: nats2
        static_ips: (( static_ips(1) ))

  - name: ruby_client_z1
    instances: 12
    networks:
      - name: nats1
        static_ips: (( static_ips(2, 3, 4, 5, 14, 15, 16, 6, 7, 8, 9, 17, 18, 19)))

  - name: ruby_client_z2
    instances: 12
    networks:
      - name: nats2
        static_ips: (( static_ips(2, 3, 4, 5, 14, 15, 16, 6, 7, 8, 9, 17, 18, 19)))

  - name: yagnats_og_client_z1
    instances: 0
    networks:
      - name: nats1
        static_ips: (( static_ips(99) ))

  - name: yagnats_og_client_z2
    instances: 0
    networks:
      - name: nats2
        static_ips: (( static_ips(99) ))

  - name: yagnats_apcera_client_z1
    instances: 6
    networks:
      - name: nats1
        static_ips: (( static_ips(10, 11, 12, 13, 20, 21, 22) ))

  - name: yagnats_apcera_client_z2
    instances: 6
    networks:
      - name: nats2
        static_ips: (( static_ips(10, 11, 12, 13, 20, 21, 22) ))

compilation:
  cloud_properties:
    instance_type: c3.large
    availability_zone: us-east-1d

resource_pools:
  - name: medium_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: us-east-1d

  - name: medium_z2
    cloud_properties:
      instance_type: m3.medium
      availability_zone: us-east-1c

networks: (( merge ))
