meta:
  stemcell: (( merge ))

name: nats-stress

director_uuid: (( merge ))

releases:
  - name: nats-stress
    version: latest

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 6
  network: nats1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: true

resource_pools:
  - name: medium_z1
    network: nats1
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: medium_z2
    network: nats2
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: gnatsd_z1
    network: nats1
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: gnatsd_z2
    network: nats2
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
